### ISSUE TITLE
Folder name, post name from Fantia website, date signature. Doesn't load videos from paid posts

### ISSUE THREAD

**Issue by Caxapok-X** [bitbybyte/fantiadl#120]
This is the main issue I'm facing. FantiaDL for some reason does not load videos from paid posts. It also does not download the covers of these posts and does not create folders. If there are photos in the post, then everything loads without any obvious problems. I would also like to see the date in the folder names, there is a date under each post, I'm not a programmer, I have no idea how this can be implemented. I will be very grateful. With the date, it is much better for me to understand what year and month this post is from.

**Comment by bitbybyte** [comment]
I can't help with anything unless you provide an example URL and output of what works or doesn't.

**Comment by IIJlOXOCIIAJl** [comment]
> I can't help with anything unless you provide an example URL and output of what works or doesn't.

What link should I provide?

**Comment by IIJlOXOCIIAJl** [comment]
Now I will try to explain to make it more clear. In this case, you can do without a paid subscription, since the end result is the same. I apologize in advance for this kind of NSFW content. I couldn't find anything else. 
Link https://fantia.jp/fanclubs/20214
By executing the command fantiadl.py -d 2021-01 https://fantia.jp/fanclubs/20214
For example, if you download her free content for January 2021, then some posts will be missing, including videos that were in free posts.
They have names:
♥ (A folder with this name is not even created.) Perhaps the folder is not created because the preview of the post is not downloaded?
無料画像7枚。有料動画3つ。 (Photos are downloading but there is no video)
透明の巫女服
It would be desirable that the date was put down automatically before the title of the post. That would be more convenient.
For example:
2021-01-25 透明の巫女服
![213121](https://github.com/bitbybyte/fantiadl/assets/95716704/d801c501-5498-4e26-9635-708318ba82fd)

**Comment by IIJlOXOCIIAJl** [comment]
> I can't help with anything unless you provide an example URL and output of what works or doesn't.

Are you here ? 😪

**Comment by bitbybyte** [comment]
Closing as outdated and can't repo

**Comment by Caxapok-X** [comment]
Everything is fine. I've already done this on my own. I can't wait a whole year for an answer. Besides, you didn't answer.
