### ISSUE TITLE
Retrieve data sorted by “update date” and support skipping certain content by date

### ISSUE THREAD

**Issue by 1223334444abc** [bitbybyte/fantiadl#125]
I noticed that Fantia currently supports sorting posts by “update date”. From a certain perspective, this means we can set a date and only retrieve content updated after this date.

This could also somewhat solve the problem mentioned in https://github.com/bitbybyte/fantiadl/issues/87.

This is very important as it can significantly reduce the time taken to update the database.

In addition, I’m not sure how the program handles posts that have had some content deleted during an update? I hope to preserve as much content as possible.

**Comment by bitbybyte** [comment]
Posts by default are already retrieverd by update date, so I'm not sure what you're suggesting? There isn't an API for fanclub posts, which is why we pull posts straight from the HTML:

https://github.com/bitbybyte/fantiadl/blob/master/models.py#L326

That is what already enables us to filter by download month:

```
   -d %Y-%m, --download-month %Y-%m
                        download posts only from a specific month, e.g. 2007-08 (excludes -n)
```

There isn't a database that is used to track posts currently, that's what #116 will be for (which I will get around to merging at some point, d'oh). That does the sort of download skipping you're asking for here. You can already use the branch directly or wait for me to merge it.

> In addition, I’m not sure how the program handles posts that have had some content deleted during an update? I hope to preserve as much content as possible.

Post contents are always retained if they're deleted on Fantia.
